In [1]:
import numpy as np
import pandas as pd

Notebook to explore the data

In [2]:
images_df = pd.read_csv("../data/images.csv")
styles_df = pd.read_csv("../data/styles.csv")

In [3]:
images_df.head(5)

    filename                                               link
0  15970.jpg  http://assets.myntassets.com/v1/images/style/p...
1  39386.jpg  http://assets.myntassets.com/v1/images/style/p...
2  59263.jpg  http://assets.myntassets.com/v1/images/style/p...
3  21379.jpg  http://assets.myntassets.com/v1/images/style/p...
4  53759.jpg  http://assets.myntassets.com/v1/images/style/p...

In [4]:
styles_df.head(5)

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011.0,Casual,Turtle Check Men Navy Blue Shirt
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012.0,Casual,Peter England Men Party Blue Jeans
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Titan Women Silver Watch
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011.0,Casual,Manchester United Men Solid Black Track Pants
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012.0,Casual,Puma Men Grey T-shirt

The id's column in styles df match up with filename of images df so we can merge the two dfs. First we need to do some cleaning on the filename so we can merge.

In [7]:
images_df["file_id"] = images_df["filename"].apply(lambda x: int(x.split(".")[0]))

images_df.head(5)

    filename                                               link  file_id
0  15970.jpg  http://assets.myntassets.com/v1/images/style/p...    15970
1  39386.jpg  http://assets.myntassets.com/v1/images/style/p...    39386
2  59263.jpg  http://assets.myntassets.com/v1/images/style/p...    59263
3  21379.jpg  http://assets.myntassets.com/v1/images/style/p...    21379
4  53759.jpg  http://assets.myntassets.com/v1/images/style/p...    53759

In [8]:
combined_df = pd.merge(images_df, styles_df, left_on="file_id", right_on="id")

combined_df.head(5)

,filename,link,file_id,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName
0,15970.jpg,http://assets.myntassets.com/v1/images/style/p...,15970,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011.0,Casual,Turtle Check Men Navy Blue Shirt
1,39386.jpg,http://assets.myntassets.com/v1/images/style/p...,39386,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012.0,Casual,Peter England Men Party Blue Jeans
2,59263.jpg,http://assets.myntassets.com/v1/images/style/p...,59263,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Titan Women Silver Watch
3,21379.jpg,http://assets.myntassets.com/v1/images/style/p...,21379,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011.0,Casual,Manchester United Men Solid Black Track Pants
4,53759.jpg,http://assets.myntassets.com/v1/images/style/p...,53759,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012.0,Casual,Puma Men Grey T-shirt